"""Add collection and sharing functionality

Revision ID: 2e55109d9de8
Revises: f4e8fe16e111
Create Date: 2025-05-16 18:23:56.141151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e55109d9de8'
down_revision = 'f4e8fe16e111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_ID'], ['user.user_ID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shared_link',
    sa.Column('link_id', sa.String(length=36), nullable=False),
    sa.Column('user_ID', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_ID'], ['user.user_ID'], ),
    sa.PrimaryKeyConstraint('link_id')
    )
    op.create_table('collection_card',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.card_ID'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.PrimaryKeyConstraint('collection_id', 'card_id')
    )
    op.create_table('shared_link_card',
    sa.Column('link_id', sa.String(length=36), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.card_ID'], ),
    sa.ForeignKeyConstraint(['link_id'], ['shared_link.link_id'], ),
    sa.PrimaryKeyConstraint('link_id', 'card_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_link_card')
    op.drop_table('collection_card')
    op.drop_table('shared_link')
    op.drop_table('collection')
    # ### end Alembic commands ###
