"""Add collections and card_collections tables

Revision ID: 47cf76424c91
Revises: 95c3cebaa1fb
Create Date: 2025-05-15 08:40:06.017883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47cf76424c91'
down_revision = '95c3cebaa1fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('collection_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_ID'], ['user.user_ID'], ),
    sa.PrimaryKeyConstraint('collection_ID')
    )
    op.create_table('collection_card',
    sa.Column('collection_ID', sa.Integer(), nullable=False),
    sa.Column('card_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_ID'], ['card.card_ID'], ),
    sa.ForeignKeyConstraint(['collection_ID'], ['collection.collection_ID'], ),
    sa.PrimaryKeyConstraint('collection_ID', 'card_ID')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    op.drop_table('collection_card')
    op.drop_table('collection')
    # ### end Alembic commands ###
