"""Add new fields to Card model

Revision ID: 762975f5727f
Revises: bda05d45e06b
Create Date: 2025-05-11 13:35:28.437285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762975f5727f'
down_revision = 'bda05d45e06b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('set_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('set_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('collector_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('mana_cost', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cmc', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('type_line', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('oracle_text', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('power', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('toughness', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('image_uris', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('color_identity', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('lang', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('lang')
        batch_op.drop_column('color_identity')
        batch_op.drop_column('image_uris')
        batch_op.drop_column('toughness')
        batch_op.drop_column('power')
        batch_op.drop_column('oracle_text')
        batch_op.drop_column('type_line')
        batch_op.drop_column('cmc')
        batch_op.drop_column('mana_cost')
        batch_op.drop_column('collector_number')
        batch_op.drop_column('set_name')
        batch_op.drop_column('set_code')

    # ### end Alembic commands ###
