"""Sync models with current schema

Revision ID: 95c3cebaa1fb
Revises: c9a5c9a0bbfd
Create Date: 2025-05-12 10:22:53.538485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c3cebaa1fb'
down_revision = 'c9a5c9a0bbfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('user_ID'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('card',
    sa.Column('card_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('rarity', sa.String(length=50), nullable=True),
    sa.Column('user_ID', sa.Integer(), nullable=False),
    sa.Column('set_code', sa.String(length=50), nullable=True),
    sa.Column('set_name', sa.String(length=100), nullable=True),
    sa.Column('collector_number', sa.String(length=20), nullable=True),
    sa.Column('mana_cost', sa.String(length=50), nullable=True),
    sa.Column('cmc', sa.Float(), nullable=True),
    sa.Column('type_line', sa.String(length=100), nullable=True),
    sa.Column('oracle_text', sa.String(length=255), nullable=True),
    sa.Column('power', sa.String(length=20), nullable=True),
    sa.Column('toughness', sa.String(length=20), nullable=True),
    sa.Column('image_uris', sa.Text(), nullable=True),
    sa.Column('color_identity', sa.String(length=50), nullable=True),
    sa.Column('lang', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_ID'], ['user.user_ID'], ),
    sa.PrimaryKeyConstraint('card_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    op.drop_table('user')
    # ### end Alembic commands ###
