"""Updated table definitions for User and Card

Revision ID: c9a5c9a0bbfd
Revises: b4d8dcf71830
Create Date: 2025-05-12 09:14:25.261270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9a5c9a0bbfd'
down_revision = 'b4d8dcf71830'
branch_labels = None
depends_on = None


def upgrade():
  
    op.rename_table('user', 'User')
    


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_ID', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('user_ID'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.rename_table('User', 'user')
    

   
