"""Add SharedLink model and join table

Revision ID: dea0c1bbe1fc
Revises: daecdf740825
Create Date: 2025-05-15 22:43:41.176241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea0c1bbe1fc'
down_revision = 'daecdf740825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_link',
    sa.Column('link_id', sa.String(length=36), nullable=False),
    sa.Column('user_ID', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_ID'], ['user.user_ID'], ),
    sa.PrimaryKeyConstraint('link_id')
    )
    op.create_table('shared_link_card',
    sa.Column('link_id', sa.String(length=36), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.card_ID'], ),
    sa.ForeignKeyConstraint(['link_id'], ['shared_link.link_id'], ),
    sa.PrimaryKeyConstraint('link_id', 'card_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_link_card')
    op.drop_table('shared_link')
    # ### end Alembic commands ###
