"""Add acquisition_price and current_price to Card model

Revision ID: f4e8fe16e111
Revises: 47cf76424c91
Create Date: 2025-05-15 21:00:59.359577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4e8fe16e111'
down_revision = '47cf76424c91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection')
    op.drop_table('collection_card')
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('acquisition_price', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('current_price', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('acquisition_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('acquisition_date')
        batch_op.drop_column('current_price')
        batch_op.drop_column('acquisition_price')
        batch_op.drop_column('price')

    op.create_table('collection_card',
    sa.Column('collection_ID', sa.INTEGER(), nullable=False),
    sa.Column('card_ID', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['card_ID'], ['card.card_ID'], ),
    sa.ForeignKeyConstraint(['collection_ID'], ['collection.collection_ID'], ),
    sa.PrimaryKeyConstraint('collection_ID', 'card_ID')
    )
    op.create_table('collection',
    sa.Column('collection_ID', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('user_ID', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_ID'], ['user.user_ID'], ),
    sa.PrimaryKeyConstraint('collection_ID')
    )
    # ### end Alembic commands ###
